# Generated by Django 2.2.24 on 2023-03-13 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pokemon_entities', '0006_auto_20230313_1449'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pokemonentity',
            name='Defence',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='pokemonentity',
            name='Health',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='pokemonentity',
            name='Level',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='pokemonentity',
            name='Stamina',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='pokemonentity',
            name='Strength',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
