# Generated by Django 2.2.24 on 2023-03-14 16:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pokemon_entities', '0016_auto_20230314_1858'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pokemon',
            old_name='previous_evolution',
            new_name='previous_evolutions',
        ),
    ]
